#                                  ______
#    _____________________________/::'   \
#   /:'   \::'    \::'    \::' _  \:' |   \
#  /:' |   \'  -   \'    | \:'   __\_     / n9! -- [ hyprpaper ]
# +\___|___/_______/_______/_______/_____/------------------------------------------------------------------+

preload = ~/.local/wallpapers/purple-planet.png
wallpaper =,~/.local/wallpapers/purple-planet.png
splash = false
