user: 230
group: 245
permission:
  read: 244
  write: 244
  exec: 244
  exec-sticky: 244
  no-access: 244
  octal: 244
  acl: 244
  context: 244
date:
  hour-old: 108
  day-old: 108
  older: 108
size:
  none: 248
  small: 248
  medium: 248
  large: 248
inode:
  valid: 13
  invalid: 248
links:
  valid: 13
  invalid: 248
tree-edge: 248
git-status:
  default: 248
  unmodified: 248
  ignored: 248
  new-in-index: dark_green
  new-in-workdir: dark_green
  typechange: dark_yellow
  deleted: dark_red
  renamed: dark_green
  modified: dark_yellow
  conflicted: dark_red