user: 105
group: 103
permission:
  read: 245
  write: 245
  exec: 245
  exec-sticky: 245
  no-access: 245
  octal: 245
  acl: 245
  context: 245
date:
  hour-old: 247
  day-old: 247
  older: 247
size:
  none: 245
  small: 147
  medium: 147
  large: 147
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
git-status:
  default: 245
  unmodified: 245
  ignored: 245
  new-in-index: dark_green
  new-in-workdir: dark_green
  typechange: dark_yellow
  deleted: dark_red
  renamed: dark_green
  modified: dark_yellow
  conflicted: dark_red