preload = ~/Documents/customization/wallpaper/monochrome/wallhaven-w88jpp.jpg
wallpaper = eDP-1,~/Documents/customization/wallpaper/monochrome/wallhaven-w88jpp.jpg
splash = false


#preload = /home/upgrad3/Documents/customization/wallpaper/jqgyba3s1wxa1.png
#wallpaper = eDP-1,/home/upgrad3/Documents/customization/wallpaper/jqgyba3s1wxa1.pngzS


